export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT;
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID;
export const APPWRITE_DATABASE_ID =
  process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID;
export const APPWRITE_TABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_TABLE_ID;

// api
export const APPWRITE_API_KEY = process.env.NEXT_PUBLIC_APPWRITE_API_KEY;
